#ifndef event_h
#define event_h

typedef enum EVENT_TYPE event_type_t;

/* Return the name of the given event. */
const char* event_name(event_type_t type);

/* All the event numbers used by the simulation are defined here. */

// Event 0, ROOTSIM_INIT (aka INIT) is used by ROOT-Sim
#define FOREACH_EVENT(FUNC) \
	FUNC(ROOTSIM_INIT) \
	\
	FUNC(CPU_LOCK) \
	FUNC(CPU_UNLOCK) \
	FUNC(CPU_FREE_CORE) \
	FUNC(CPU_EVENT) \
	FUNC(CPU_STATS) \
	FUNC(CPU_NO_EVENT) \
	FUNC(CPU_LOCK_LOCK) \
	FUNC(CPU_LOCK_UNLOCK) \
	FUNC(CPU_RWLOCK_READ_LOCK) \
	FUNC(CPU_RWLOCK_READ_UNLOCK) \
	FUNC(CPU_RWLOCK_WRITE_LOCK) \
	FUNC(CPU_RWLOCK_WRITE_UNLOCK) \
	\
	FUNC(GR_GET_REQUEST) \
	FUNC(GR_FORWARD_GET_REQUEST_LOCKED) \
	FUNC(GR_GET_REQUEST_LOCKED) \
	FUNC(GR_GET_REQUEST_UNLOCKED) \
	FUNC(GR_GET_RESPONSE) \
	FUNC(GR_PUT_REQUEST) \
	FUNC(GR_PUT_REQUEST_LOCKED) \
	FUNC(GR_PUT_REQUEST_UNLOCKED) \
	FUNC(GR_PUT_RESPONSE) \
	FUNC(GR_REPLICA_UPDATE) \
	FUNC(GR_REPLICA_UPDATE_LOCKED) \
	FUNC(GR_REPLICA_UPDATE_UNLOCKED) \
	FUNC(GR_LST_FROM_LEAF) \
	FUNC(GR_LST_FROM_LEAF_ROOT_LOCKED) \
	FUNC(GR_LST_FROM_LEAF_ROOT_UNLOCKED) \
	FUNC(GR_START_GST_COMPUTATION) \
	FUNC(GR_GST_FROM_ROOT) \
	FUNC(GR_GST_FROM_ROOT_LOCKED) \
	FUNC(GR_GST_FROM_ROOT_UNLOCKED) \
	FUNC(GR_GET_SNAPSHOT_REQUEST) \
	FUNC(GR_GET_SNAPSHOT_REQUEST_LOCKED) \
	FUNC(GR_GET_SNAPSHOT_REQUEST_UNLOCKED) \
	FUNC(GR_GET_SNAPSHOT_RESPONSE) \
	FUNC(GR_SLICE_REQUEST) \
	FUNC(GR_SLICE_REQUEST_LOCKED) \
	FUNC(GR_SLICE_REQUEST_UNLOCKED) \
	FUNC(GR_SLICE_RESPONSE) \
	FUNC(GR_SLICE_RESPONSE_LOCKED) \
	FUNC(GR_SLICE_RESPONSE_UNLOCKED) \
	FUNC(GR_ROTX_REQUEST) \
	FUNC(GR_ROTX_RESPONSE) \
	FUNC(GR_CLOCK_TICK) \
	FUNC(GR_CLOCK_TICK_LOCKED) \
	FUNC(GR_CLOCK_TICK_UNLOCKED) \
	FUNC(GR_HEARTBEAT) \
	FUNC(GR_HEARTBEAT_LOCKED) \
	\
	FUNC(GRV_FORWARDED_GET_REQUEST_LOCKED) \
	FUNC(GRV_GET_REQUEST) \
	FUNC(GRV_FORWARD_GET_REQUEST_LOCKED) \
	FUNC(GRV_GET_REQUEST_LOCKED) \
	FUNC(GRV_GET_REQUEST_UNLOCKED) \
	FUNC(GRV_GET_RESPONSE) \
	FUNC(GRV_PUT_REQUEST) \
	FUNC(GRV_PUT_REQUEST_LOCKED) \
	FUNC(GRV_PUT_REQUEST_UNLOCKED) \
	FUNC(GRV_PUT_RESPONSE) \
	FUNC(GRV_REPLICA_UPDATE) \
	FUNC(GRV_REPLICA_UPDATE_VV_LOCKED) \
	FUNC(GRV_REPLICA_UPDATE_VV_UNLOCKED) \
	FUNC(GRV_SLICE_REQUEST) \
	FUNC(GRV_SLICE_REQUEST_LOCKED) \
	FUNC(GRV_SLICE_REQUEST_UNLOCKED) \
	FUNC(GRV_SLICE_RESPONSE) \
	FUNC(GRV_ROTX_REQUEST) \
	FUNC(GRV_ROTX_REQUEST_LOCKED) \
	FUNC(GRV_ROTX_REQUEST_UNLOCKED) \
	FUNC(GRV_ROTX_RESPONSE) \
	FUNC(GRV_CLOCK_TICK) \
	FUNC(GRV_CLOCK_TICK_LOCKED) \
	FUNC(GRV_CLOCK_TICK_UNLOCKED) \
	FUNC(GRV_HEARTBEAT) \
	FUNC(GRV_HEARTBEAT_LOCKED) \
	FUNC(GRV_START_GST_COMPUTATION) \
	FUNC(GRV_LST_FROM_LEAF) \
	FUNC(GRV_LST_FROM_LEAF_ROOT_LOCKED) \
	FUNC(GRV_LST_FROM_LEAF_ROOT_UNLOCKED) \
	FUNC(GRV_GST_FROM_ROOT) \
	FUNC(GRV_GST_FROM_ROOT_LOCKED) \
	FUNC(GRV_GST_FROM_ROOT_UNLOCKED) \
	\
	FUNC(CLIENT_TICK) \
	\
	FUNC(NUM_EVENT_TYPES) // Must be the last element

#define ENUM_ITEM(I) I,

enum EVENT_TYPE {
	FOREACH_EVENT(ENUM_ITEM)
};

#ifndef event_c
#undef FOREACH_EVENT
#undef ENUM_ITEM
#endif

#endif
